/*
  The catalog as the site reads it.

  src/data/catalog.json is generated by scripts/build-catalog.mjs and
  scripts/optimize-images.mjs. It is the light index (cards, filters, search).
  The heavier detail of one product (variants, features, sizing) is fetched
  from public/data/p/<slug>.json when its page opens.
*/
import raw from "./catalog.json";
import type { RegionSlug } from "./taxonomy";
import { cdnUrl } from "../lib/cdn";

export type Product = {
  slug: string;
  title: string;
  subtitle: string;
  brand: string;
  brandSlug: string;
  region: RegionSlug;
  category: string;
  priceMin: number;
  priceMax: number;
  available: boolean;
  variantCount: number;
  conditions: string[];
  hcpcs: string[];
  summary: string;
  images: number;
  renewed: boolean;
  addedAt: string;
};

export type Variant = { o: string[]; p: number; s: string; a: boolean };
export type Feature = { label?: string; text: string };
export type ProductDetail = {
  slug: string;
  optionNames: string[];
  variants: Variant[];
  features: Feature[];
  indications: string[];
  measurement: string;
  conditions: string[];
  hcpcs: string[];
};

type Raw = {
  products: Product[];
  conditions: { name: string; slug: string; count: number }[];
  categories: Record<string, string>;
};
const data = raw as Raw;

export const PRODUCTS: Product[] = data.products;
export const CONDITIONS = data.conditions;
export const CATEGORY_NAMES: Record<string, string> = data.categories;

const bySlug = new Map(PRODUCTS.map((p) => [p.slug, p]));
export const productBySlug = (slug: string) => bySlug.get(slug);

export const categoryName = (slug: string) => CATEGORY_NAMES[slug] ?? slug;

/* "Walker Boot" becomes "Walker Boots"; a few names need their own plural. */
export function pluralCategory(name: string) {
  if (/(Therapy|Accessories)$/.test(name)) return name;
  if (/Orthosis$/.test(name)) return name.replace(/Orthosis$/, "Orthoses");
  if (/(TLSO|Spica)$/.test(name)) return `${name} Braces`;
  return `${name}s`;
}
export const conditionBySlug = (slug: string) => CONDITIONS.find((c) => c.slug === slug);

export type Brand = { name: string; slug: string; count: number };
export const BRANDS: Brand[] = (() => {
  const m = new Map<string, Brand>();
  for (const p of PRODUCTS) {
    const b = m.get(p.brandSlug) ?? { name: p.brand, slug: p.brandSlug, count: 0 };
    b.count++;
    m.set(p.brandSlug, b);
  }
  return [...m.values()].sort((a, b) => b.count - a.count);
})();
export const brandBySlug = (slug: string) => BRANDS.find((b) => b.slug === slug);

/* Categories that actually hold products, largest first. */
export const CATEGORIES = (() => {
  const counts = new Map<string, number>();
  for (const p of PRODUCTS) counts.set(p.category, (counts.get(p.category) ?? 0) + 1);
  return [...counts.entries()]
    .map(([slug, count]) => ({ slug, name: categoryName(slug), count }))
    .sort((a, b) => b.count - a.count);
})();

/* Cards use 480px, the product page 900px: the same widths as the local files. */
export const imageSrc = (p: Pick<Product, "slug">, n = 1, size: "sm" | "lg" = "sm") =>
  cdnUrl(`products/${p.slug}/${n}`, size === "sm" ? 480 : 900, `/products/${p.slug}/${n}${size === "sm" ? "-sm" : ""}.webp`);

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
export const money = (n: number) => usd.format(n);
export const priceLabel = (p: Pick<Product, "priceMin" | "priceMax">) =>
  p.priceMin === p.priceMax ? money(p.priceMin) : `From ${money(p.priceMin)}`;

/*
  A steady "featured" order: complete listings first (photo, in stock, a real
  device rather than a spare part), then a fixed shuffle so one brand does not
  fill the first screen. Deterministic, so the prerendered order and the live
  order agree.
*/
function hash(s: string) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}
export function featuredScore(p: Product) {
  let s = 0;
  if (p.images > 0) s += 4;
  if (p.images > 1) s += 1;
  if (p.available) s += 3;
  if (p.category !== "parts-accessories") s += 3;
  if (p.conditions.length) s += 1;
  return s * 1e10 + (hash(p.slug) % 1e10);
}

export type SortKey = "featured" | "price-asc" | "price-desc" | "name" | "newest";
export function sortProducts(list: Product[], key: SortKey) {
  const out = [...list];
  switch (key) {
    case "price-asc":
      return out.sort((a, b) => a.priceMin - b.priceMin);
    case "price-desc":
      return out.sort((a, b) => b.priceMin - a.priceMin);
    case "name":
      return out.sort((a, b) => a.title.localeCompare(b.title));
    case "newest":
      return out.sort((a, b) => b.addedAt.localeCompare(a.addedAt));
    default:
      return out.sort((a, b) => featuredScore(b) - featuredScore(a));
  }
}

export function related(p: Product, limit = 8) {
  const same = PRODUCTS.filter((x) => x.slug !== p.slug && x.region === p.region && x.category !== "parts-accessories");
  const score = (x: Product) =>
    (x.category === p.category ? 4 : 0) +
    x.conditions.filter((c) => p.conditions.includes(c)).length +
    (x.images > 0 ? 1 : 0);
  return same.sort((a, b) => score(b) - score(a) || featuredScore(b) - featuredScore(a)).slice(0, limit);
}

export async function loadDetail(slug: string): Promise<ProductDetail | null> {
  try {
    const res = await fetch(`/data/p/${slug}.json`);
    if (!res.ok) return null;
    return (await res.json()) as ProductDetail;
  } catch {
    return null;
  }
}

export const slugifyCondition = (name: string) =>
  name
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

/* What a body region holds: its categories and its most common conditions. */
export function regionFacets(region: string) {
  const list = PRODUCTS.filter((p) => p.region === region);
  const cats = new Map<string, number>();
  const conds = new Map<string, number>();
  for (const p of list) {
    cats.set(p.category, (cats.get(p.category) ?? 0) + 1);
    for (const c of p.conditions) conds.set(c, (conds.get(c) ?? 0) + 1);
  }
  return {
    count: list.length,
    categories: [...cats.entries()].sort((a, b) => b[1] - a[1]).map(([slug, count]) => ({ slug, name: categoryName(slug), count })),
    conditions: [...conds.entries()]
      .filter(([name]) => !/^post-surgical/i.test(name))
      .sort((a, b) => b[1] - a[1])
      .map(([name, count]) => ({ name, slug: slugifyCondition(name), count })),
  };
}
